name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build and test
        run: npm run build
          
      - name: Deploy
        run: ./deploy-script.sh
        
      - name: Notify on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: failure
          message: 'Build or deployment failed'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
